#!/bin/bash

#PBS -N PLAN
#PBS -l nodes=1:ppn=1
#PBS -l vmem=4gb
#PBS -l walltime=0:40:00
#PBS -j oe
#PBS -M z3403159@student.unsw.edu.au
#PBS -m ae

module purge
module add python/3.6.5

RESP_DIR="$PBS_O_HOME/RESP"
SW_DIR="$PBS_O_HOME/RESP/pywde"

mkdir -p $RESP_DIR/pngs
cd $RESP_DIR

. $SW_DIR/.venv/bin/activate
export PYTHONPATH=$SW_DIR
export LC_ALL=en_AU.utf8
export LANG=en_AU.utf8
python $SW_DIR/runit.py run-with $DIST_CODE $WAVELET $NUM $I0 $ID $JA $JB $JC

